sudo: false
language: java
jdk:
  - openjdk8
before_install:
  - echo "No pre-installs at this time"

install: true

env:
  - CI_CLEANUP=ci/tmp/cleanup.sh

script:
  - mkdir -p "${CI_CLEANUP%/*}" && touch "$CI_CLEANUP" && chmod +x "$CI_CLEANUP"
  - ci/run-tests.sh
  - mvn clean install -DskipTests
  - ci/run-samples-tests.sh
after_success:
  - echo "Test Success - Branch( $TRAVIS_BRANCH ) Pull Request( $TRAVIS_PULL_REQUEST ) Tag( $TRAVIS_TAG )"

after_script:
  - $CI_CLEANUP
  # Need to give some time for output buffer to finish
  - sleep 10
