sudo: false
language: java
jdk:
  - openjdk8
before_install:
  - echo "No pre-installs at this time"

install: true

script:
  - ci/run-tests.sh
  - mvn clean install -DskipTests
  - ci/run-samples-tests.sh
after_success:
  - echo "Test Success - Branch( $TRAVIS_BRANCH ) Pull Request( $TRAVIS_PULL_REQUEST ) Tag( $TRAVIS_TAG )"
